server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    username: root
    password: xinzi15078372389
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&severTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 配置hystrix dashboard，开启监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream